services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
      - ./models:/app/models
    environment:
      - GIN_MODE=debug
    networks:
      - owngpt-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "9090:9090"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - owngpt-network
    restart: unless-stopped

networks:
  owngpt-network:
    driver: bridge

volumes:
  models:
    driver: local
